version: '3'
services:
  vector-search-server:
    build:
      context: .
      dockerfile: Dockerfile.vector_server
    container_name: vector-search-server
    image: registry.infra.music-flo.io/reco/rag-vector-server
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7080", "--workers", "4"]
    ports:
      - '7080:7080'
    environment:
      - BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - DATASTORE=pinecone
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=d607d7b6-5fd3-4c64-aa61-6b155c5887d1
      - PINECONE_ENVIRONMENT=us-central1-gcp
      - PINECONE_INDEX=open-ai-index
  prompt-server:
    build:
      context: .
      dockerfile: Dockerfile.prompt_server
    container_name: prompt-server
    image: registry.infra.music-flo.io/reco/rag-prompt-server
    command: ["uvicorn", "prompt_server.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4"]
    ports:
      - '8001:8001'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    links:
      - vector-search-server