FROM python:3.10

ENV WORKDIR=/app
WORKDIR $WORKDIR

COPY vector_server $WORKDIR/
COPY vector-server-requirements.txt $WORKDIR/vector-server-requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:$WORKDIR/vector_server"

RUN pip install -r vector-server-requirements.txt